version: '3'
services:
  backend-dev-server:
    build:
      context: .
      dockerfile: backend/Dockerfile.dev
    ports:
      - 8000:8000
    volumes:
      - ./:/code
  frontend-dev-server:
    build:
      context: .
      dockerfile: frontend/Dockerfile.dev
    ports:
      - 5173:5173
      - 4173:4173
    volumes:
      - ./:/code
